### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by Croydon** [SpartanJ/SOIL2#32]
Please add a LICENSE file with the license/copyright information

This way it can be detected easier automatically and it is easier to copy these information for packaging purposes

**Comment by r-lyeh** [comment]
UNLICENSE !

**Comment by Croydon** [comment]
Not everything is public domain

https://github.com/SpartanJ/SOIL2/blob/79fe89289aa6e7677110ec090d3be813d145de32/src/SOIL2/etc1_utils.c
https://github.com/SpartanJ/SOIL2/blob/79fe89289aa6e7677110ec090d3be813d145de32/src/SOIL2/etc1_utils.h

But even if the file just mentions these two files + states that the rest is public domain would already help

**Comment by SpartanJ** [comment]
I would love to keep it public domain or as permissive as possible! But as @Croydon says I'm kinda blocked by the ETC1 decompressor.
My main issue with [rg_etc1](https://github.com/richgel999/rg-etc1/) and #33 is that it uses C++, and SOIL2 is pure C... and worries me that this could discourage the use in some cases, and I don't want to break anyone project because they are already using it as a C library.
I think the best option is to migrate the [rg_etc1](https://github.com/richgel999/rg-etc1/) code to C and make this library follow that library its license, which is zlib.
Please let me know what you think about it. I'm totally open to new ideas.
In the meantime, I don't know if makes sense to add a LICENSE file until this is decided.

**Comment by r-lyeh** [comment]
What about this UNLICENSE file until you address #33 ?

```
All files in this package (except etc1_utils.h and etc1_utils.c) are licensed to the UNLICENSE terms found below.
etc1_utils.h and etc1_utils.c files are licensed under Apache2 license.

---

This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.

In jurisdictions that recognize copyright laws, the author or authors
of this software dedicate any and all copyright interest in the
software to the public domain. We make this dedication for the benefit
of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of
relinquishment in perpetuity of all present and future rights to this
software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to <http://unlicense.org/>
```

**Comment by SpartanJ** [comment]
That's good enough for me. [Added the LICENSE file](https://github.com/SpartanJ/SOIL2/commit/e4fc62c379bd436259f6e0af1926f62121a30c48).
For the moment I'll keep it this way until I find a solution for the ETC1 code.
Anyway, I'm not against any license that requires attribution to its authors. Is there any legal problem with attribution in licenses like MIT? I know very little about licenses.

**Comment by SpartanJ** [comment]
Changed the license to [MIT-0](https://github.com/aws/mit-0) thanks to closing #33. Thanks @Croydon and @r-lyeh !
