### ISSUE TITLE
weird linking errors

### ISSUE THREAD

**Issue by DanielLuther** [SpartanJ/SOIL2#39]
I don't even know how to describe whats wrong cause I don't know 

but I keep getting these errors

LNK2019	unresolved external symbol SOIL_free_image_data referenced in function "unsigned int __cdecl TextureFromFile(char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?TextureFromFile@@YAIPEBDAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z)

LNK2019	unresolved external symbol SOIL_load_image referenced in function "unsigned int __cdecl TextureFromFile(char const *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?TextureFromFile@@YAIPEBDAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z)

and they wont do away. I have googled the problem but didn't get an answer. I have google and made sure I set SOIL2 up properly I don't know what I did wrong or how to fix the problem.

**Comment by SpartanJ** [comment]
You are not linking SOIL2 correctly. Sorry but this is not a support forum, this kind of issues aren't library issues, you need to set up your project correctly, maybe first take some tutorial on how to add external libraries to a VS project or something like that. You can have a working example from this repository too, by checking the generated premake4 o 5 VS project (check the test project).
I can't help much more than that since I can't see your project and I personally rarely use VS projects. Good luck!
